server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server:9000
